namespace:
  create: true
  name: microshield-bpo

replicaCount: 2

image:
  repository: microshield-bpo-site
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

containerPort: 80

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

secret:
  enabled: true
  name: ""
  data: {}
  stringData: {}

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 128Mi

health:
  path: /

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
